USE [master]
GO

/****** Object:  Database [AudioBox]    Script Date: 02/06/2022 17:22:20 ******/
CREATE DATABASE [AudioBox]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AudioBox', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\AudioBox.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AudioBox_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\AudioBox_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AudioBox].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AudioBox] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AudioBox] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AudioBox] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AudioBox] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AudioBox] SET ARITHABORT OFF 
GO

ALTER DATABASE [AudioBox] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AudioBox] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AudioBox] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AudioBox] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AudioBox] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AudioBox] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AudioBox] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AudioBox] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AudioBox] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AudioBox] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AudioBox] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AudioBox] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AudioBox] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AudioBox] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AudioBox] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AudioBox] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AudioBox] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AudioBox] SET RECOVERY FULL 
GO

ALTER DATABASE [AudioBox] SET  MULTI_USER 
GO

ALTER DATABASE [AudioBox] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AudioBox] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AudioBox] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AudioBox] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AudioBox] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AudioBox] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AudioBox] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AudioBox] SET  READ_WRITE 
GO

